# Number of replicas to deploy
replicaCount: 1

image:
  registry: registry.yunna.net
  repository: phusion/baseimage
  tag: "latest"  # Consider using a specific version instead of "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 22
  name: ssh

# Readiness probe configuration
readinessProbe:
  exec:
    command:
      - cat
      - /etc/service/sshd/down
  initialDelaySeconds: 5
  periodSeconds: 3
  failureThreshold: 6

# Liveness probe configuration
livenessProbe:
  exec:
    command:
      - cat
      - /etc/service/sshd/down
  initialDelaySeconds: 5
  periodSeconds: 3

# Resource limits and requests
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Node selector configuration
nodeSelector: {}

# Tolerations configuration
tolerations: []

# Affinity configuration
affinity: {}