name: Release Helm Charts
on:
  push:
    branches:
      - main
      - test
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Helm repositories
        run: |
          helm repo add stable https://charts.helm.sh/stable
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Update Helm chart dependencies
        run: |
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm dependency update "$chart" || true
            fi
          done

      - name: Package all Helm charts
        run: |
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm package "$chart" || true
            fi
          done

      - name: Configure git credentials
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global credential.helper store
          echo "https://${{ github.actor }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials

      - name: Push packaged charts to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone --branch gh-pages https://github.com/jianzhis/AppMirror gh-pages
          mkdir -p gh-pages/${{ github.ref_name }}
          mv *.tgz gh-pages/${{ github.ref_name }}/
          cd gh-pages
          helm repo index ${{ github.ref_name }} --url https://jianzhis.github.io/AppMirror/${{ github.ref_name }}
          git add .
          git commit -m "Publish new Helm chart versions to ${{ github.ref_name }}"
          git push