name: Helm Charts Workflow

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'charts/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'charts/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Lint Helm charts
        run: |
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm lint "$chart" || true
            fi
          done

  package-and-push-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Package and push to test directory
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git clone --branch gh-pages https://github.com/jianzhis/AppMirror gh-pages
          mkdir -p gh-pages/test
          
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm package "$chart" -d gh-pages/test
            fi
          done
          
          cd gh-pages
          helm repo index test --url https://jianzhis.github.io/AppMirror/test
          git add .
          git commit -m "Update test charts"
          git push

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: lint-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts
          charts_repo_url: https://jianzhis.github.io/AppMirror