name: Helm Chart CI/CD

on:
  push:
    branches:
      - main
      - test
    paths:
      - 'charts/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - 'charts/**'

jobs:
  basic-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Basic Helm lint
        run: |
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              helm lint "$chart" || true
            fi
          done

  release:
    needs: basic-check
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts
          charts_repo_url: https://jianzhis.github.io/AppMirror